### PR TITLE
Update picturefill.js from 2.1.0 to 2.3.0

### PR DESCRIPTION
**Pull request by seriema**
2.3.0 was released 11 days ago, but the responsiveimages.org site was still using 2.1.0 so I thought it was time to update it. Both in regular site and in demos.

### CODE REVIEW

**Comment by seriema** [comment]
Eh, that failing linthound is complaining about `picturefill.js` but I didn't write it (obviously). :panda_face:

**Comment by marcoscaceres** [comment]
I wouldn't mind just pointing to some CDN for picturefill (latest) instead of hosting it. Is there such an option?

**Comment by marcoscaceres** [comment]
Ok, should go with this instead. 
http://cdnjs.com/libraries/picturefill

**Comment by marcoscaceres** [comment]
... shame there is no "latest" link... living on the edge is fun.

**Comment by marcoscaceres** [comment]
Ok, so I'm also inclined to move to the min version. So let's just use: 
https://cdnjs.cloudflare.com/ajax/libs/picturefill/2.3.0/picturefill.min.js

**Comment by marcoscaceres** [comment]
Ok, put together the alt at #71

**Comment by seriema** [comment]
Maybe we can get cdnjs or Picturefill to add a "latest" link? I'm falling behind on my open-source-promises atm so if anyone would like to check what we would need to do to make it happen, feel free to do it.

**Pull request closed without merging**
