### PR TITLE
Switched to using CDN version of picturefill (closes #70)

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@seriema can you please check? Or any other lovely person:)

**Comment by seriema** [comment]
@marcoscaceres I cloned it locally and checked all the demos. Seems fine, no errors that I could se. :+1: 

As a sidenote, I do get some things that don't load properly (like CSS on some pages) or some links not working because there seems to be a mix of how links are written. With `/` or without, causing it to go to root sometimes and sometimes not. Want me to clean that up? =)

**Comment by marcoscaceres** [comment]
> Want me to clean that up? =)

Sure! that would be great!

**Comment by coliff** [comment]
Would be good to update again to Picturefill 2.3.1. :-)
http://scottjehl.github.io/picturefill/#download

**Comment by marcoscaceres** [comment]
@coliff, done.

**Comment by seriema** [comment]
Maybe we can get cdnjs or Picturefill to add a "latest" link (like @marcoscaceres seemed to want in #70 )? So we don't have to keep manually add these requests here. I'm falling behind on my open-source-promises atm so if anyone would like to check what we would need to do to make it happen, feel free to do it.

**Comment by marcoscaceres** [comment]
Would be great. I don't know the folks that run the CDN... @Wilto maybe?

**Comment by Wilto** [comment]
Your guess is as good as mine, honestly. We could file an issue over at https://github.com/cdnjs/cdnjs

**Comment by marcoscaceres** [comment]
@Wilto, nice! thanks for the link.

**Comment by coliff** [comment]
@Wilto @marcoscaceres I saw this requested already...
https://github.com/cdnjs/cdnjs/issues/360

**Comment by marcoscaceres** [comment]
Ok, cool... not great that it's not possible... but at least it's on the radar and a known issue.

**Pull request merged**
